"""Q7.4: build the AI usage log from the actual Claude Code session transcript.

Writes reports/ai_usage_log.md: every human prompt in order, the tool-call
volume per session, and the authorship split. The point is auditability -- the
log is generated from the transcript rather than written from memory, so it
cannot quietly disagree with what actually happened.
"""
from __future__ import annotations

import glob, json, os, re, sys
from datetime import datetime
from pathlib import Path

SKIP_PREFIXES = ("<local-command", "<command-name", "Caveat:", "<system-reminder",
                 "<task-notification>", "[Image:", "Base directory for this skill:",
                 "This session is being continued", "[Request interrupted")


def human_prompts(path: str):
    """User turns that a person actually typed (not tool results, not hooks)."""
    for line in open(path, errors="replace"):
        try:
            d = json.loads(line)
        except json.JSONDecodeError:
            continue
        if d.get("type") != "user":
            continue
        c = d.get("message", {}).get("content")
        text = c if isinstance(c, str) else None
        if text is None and isinstance(c, list):
            parts = [b.get("text", "") for b in c
                     if isinstance(b, dict) and b.get("type") == "text"]
            text = "\n".join(p for p in parts if p) or None
        if not text or text.strip().startswith(SKIP_PREFIXES):
            continue
        yield d.get("timestamp"), text.strip()


def decisions(path: str):
    """Design decisions the human made through the interactive question tool.

    These never appear as typed prompts -- they are answers to multiple-choice
    questions -- so a log built only from prompt text would credit the assistant
    with choices the human actually made.
    """
    # id -> the question texts as *asked*. Reading them from the tool input
    # rather than from the result string matters: several questions quote the
    # spec, so they contain double quotes, and a `"([^"]+)"="([^"]+)"` scan of
    # the result truncates those to an empty or one-character question.
    asked: dict[str, list[str]] = {}
    for line in open(path, errors="replace"):
        try:
            d = json.loads(line)
        except json.JSONDecodeError:
            continue
        if d.get("type") == "assistant":
            for b in d.get("message", {}).get("content", []) or []:
                if isinstance(b, dict) and b.get("type") == "tool_use" \
                        and b.get("name") == "AskUserQuestion":
                    asked[b["id"]] = [q.get("question", "")
                                      for q in (b.get("input") or {}).get("questions", [])]
        if d.get("type") == "user" and isinstance(d.get("message", {}).get("content"), list):
            for b in d["message"]["content"]:
                if isinstance(b, dict) and b.get("type") == "tool_result" \
                        and b.get("tool_use_id") in asked:
                    txt = b.get("content")
                    if isinstance(txt, list):
                        txt = " ".join(x.get("text", "") for x in txt if isinstance(x, dict))
                    txt = txt or ""
                    for q in asked[b["tool_use_id"]]:
                        key = f'"{q}"="'
                        i = txt.find(key)
                        if i < 0:
                            continue
                        j = txt.find('"', i + len(key))
                        yield q, txt[i + len(key):j if j > 0 else None]


def tool_calls(path: str) -> dict[str, int]:
    counts: dict[str, int] = {}
    for line in open(path, errors="replace"):
        try:
            d = json.loads(line)
        except json.JSONDecodeError:
            continue
        if d.get("type") != "assistant":
            continue
        for b in d.get("message", {}).get("content", []) or []:
            if isinstance(b, dict) and b.get("type") == "tool_use":
                counts[b["name"]] = counts.get(b["name"], 0) + 1
    return counts


def main(transcript_dir: str, out: Path):
    files = sorted(glob.glob(os.path.join(transcript_dir, "*.jsonl")), key=os.path.getmtime)
    if not files:
        # the transcripts live on the machine the assistant ran on, not on the
        # compute host, so this is a skip rather than a failure
        print(f"no transcripts under {transcript_dir} -- run `make ai-log` where "
              f"Claude Code ran (pass the directory as argv[1] to override)")
        return
    L = ["# AI usage log — CS4.406 Assignment 2\n",
         "**Assistant:** Claude Code (Opus 5), run from the local machine against the remote",
         "host `gvlab2` over ssh. **Human:** all prompts below, all design decisions marked",
         "*(decided by me)*, all dataset access and leaderboard submission.\n",
         "This file is generated by `scripts/ai_usage_log.py` directly from the Claude Code",
         "session transcripts, so it is a record rather than a recollection. Regenerate with",
         "`make ai-log`.\n",
         "> Assignment 1's log is a separate file in that repository; this one covers A2 only.\n",
         "## Authorship\n",
         "| area | authorship |",
         "|---|---|",
         "| Problem framing, scope, dataset/variant choices, evaluation conventions | human |",
         "| `src/newsrec/*.py`, `scripts/*.py`, `tests/*.py`, `Makefile`, `configs/*` | AI-drafted, human-reviewed |",
         "| Design decisions inside that code (Option A vs B for the re-ranker, which candidate set stage two trains on, evaluation framing, train scale for the submissions) | human, via the recorded decisions and prompts below |",
         "| Bug diagnoses and fixes (tied-timestamp tiebreak in the expanding means, clipped user lookup aliasing onto a real user, stage-1 recall degenerating to 1.0, cascade scored on the contaminated set, out-of-bounds gather surfacing as a cuBLAS error, push overwriting fresh remote results) | AI-identified, human-confirmed |",
         "| Verification of claims against the raw bundles (MIND history timestamps, history ordering, embedding coverage) | AI-run, reported with the controls that invalidated two probes |",
         "| This report, README, design note prose | AI-drafted from measured outputs, human-reviewed |",
         "| Numbers, tables and figures | produced by the committed code; none hand-written |",
         "\n## Sessions\n"]
    total = 0
    for f in files:
        prompts = list(human_prompts(f))
        tc = tool_calls(f)
        total += len(prompts)
        span = ""
        if prompts and prompts[0][0]:
            a = prompts[0][0][:10]
            b = prompts[-1][0][:10] if prompts[-1][0] else a
            span = f" · {a} → {b}"
        L.append(f"**`{os.path.basename(f)}`** — {len(prompts)} human prompts, "
                 f"{sum(tc.values()):,} tool calls{span}  ")
        L.append("Tool calls: " + ", ".join(f"{k} {v}" for k, v in
                                            sorted(tc.items(), key=lambda x: -x[1])) + "\n")
    picks = [(q, a) for f in files for q, a in decisions(f)]
    if picks:
        L += ["\n## Design decisions made by the human, not the assistant\n",
              "Answers to multiple-choice questions the assistant raised. Recorded here",
              "because they are choices, not prompts, and would otherwise be invisible.\n",
              "| question | choice |", "|---|---|"]
        L += [f"| {q} | **{a}** |" for q, a in picks]
        L.append("")
    L.append(f"\n## Prompts, verbatim and in order ({total} total)\n")
    n = 0
    for f in files:
        for ts, text in human_prompts(f):
            n += 1
            when = ""
            if ts:
                try:
                    when = datetime.fromisoformat(ts.replace("Z", "+00:00")).strftime("%Y-%m-%d %H:%M UTC")
                except ValueError:
                    when = ts
            L.append(f"### {n}. {when}\n")
            L.append("```text")
            L.append(text)
            L.append("```\n")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L))
    print(f"wrote {out} ({total} prompts from {len(files)} session(s))")


if __name__ == "__main__":
    d = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser(
        "~/.claude/projects/-home-gokboru-Documents-Course-Work-M26-IRE-Assignments-assignment-1")
    main(d, Path(sys.argv[2] if len(sys.argv) > 2 else "reports/ai_usage_log.md"))
