"""Q3: baseline reproduced, improved, ablated, with CIs. Generated from JSONs."""
from __future__ import annotations
import argparse, json
from pathlib import Path

DS = ("ebnerd", "mind")
L = {"ebnerd": "EB-NeRD", "mind": "MIND"}


def load(p): return json.loads(p.read_text()) if p.exists() else None
def f4(x): return "--" if x is None else f"{x:.4f}"


def ci(r):
    if not r: return "--"
    lo, hi = r["ci95"]
    star = "" if r["excludes_zero"] else " *spans 0*"
    return f"{r['delta']:+.4f} [{lo:+.4f}, {hi:+.4f}]{star}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", default="small")
    ap.add_argument("--out", type=Path, default=Path("reports/q3/q3_baseline.md"))
    a = ap.parse_args()
    q3 = Path("reports/q3")
    nrms = {d: load(q3 / f"nrms_{d}_{a.variant}.json") for d in DS}
    abl = {d: load(q3 / f"ablation_{d}_{a.variant}.json") for d in DS}

    o = ["# Q3 — Baseline reproduced, then beaten", "",
         f"Dev scale (`{a.variant}`), both datasets. Generated by `scripts/q3_report.py`.", "",
         "## Q3.1 — The starter baseline, reproduced", "",
         "NRMS-docvec from `ebnerd-benchmark`, ported to PyTorch layer for layer.",
         "The starter is TensorFlow and pins `polars==0.20.8`, `numpy<1.26.1`,",
         "`torch<2.3`, which will not co-install with this stack and will not run",
         "on this card. A frozen parallel environment would reproduce the *code*",
         "while making every number incomparable — different feature store,",
         "different splits, different metric implementation. So the architecture",
         "is ported and the *inputs and metrics are shared* with the rest of the",
         "assignment: same article vectors, same temporal splits, and A1's harness,",
         "which `tests/test_official_metrics.py` validates against `ebrec`'s own",
         "metric code.", "",
         "Hyperparameters are the starter's: history 20, npratio 4, lr 1e-4,",
         "16 heads x 16 dims, attention hidden 200, dropout 0.2, news encoder",
         "[512, 512, 512], L2 1e-4 on the news-encoder Linear weights only.", "",
         "One deliberate deviation: the history attention is **masked**. The starter",
         "pads to `history_size` without masking, letting a user with 3 clicks have",
         "17 pad vectors vote in the softmax.", "",
         "## Q3.2 — One principled change: freshness weighting", "",
         "NRMS sees only document vectors, so it cannot know that an article is four",
         "days old on a corpus whose median clicked article is 80 hours young, nor",
         "that nobody has clicked it. A small head over those scalars is added to",
         "the dot-product score — additive and zero-initialised, so the improved",
         "model *starts* as the baseline and the ablation isolates the change",
         "rather than comparing two unrelated training runs.", "",
         "| | model | AUC | MRR | nDCG@5 | nDCG@10 |", "|---|---|---|---|---|---|"]
    for d in DS:
        j = nrms.get(d)
        if not j: continue
        for n, r in j["results"].items():
            o.append(f"| {L[d]} | {n} | {f4(r['auc'])} | {f4(r['mrr'])} | "
                     f"{f4(r['ndcg@5'])} | {f4(r['ndcg@10'])} |")
    o += ["", "## Q3.3 — Ablation isolating the improvement", "",
          "Two axes are kept apart. Conflating them would report one number for",
          "two changes, which is what Q3.3 forbids.", "",
          "**Axis 1 — architecture** (same features, different model):", "",
          "| | A1 emb | NRMS | GBDT |", "|---|---|---|---|"]
    from itertools import chain
    q2 = Path("reports/q2")
    for d in DS:
        j, n = load(q2 / f"rerank_{d}_{a.variant}_shipped.json"), nrms.get(d)
        if not j: continue
        o.append(f"| {L[d]} | {f4(j['results']['emb']['auc'])} | "
                 f"{f4(n['results']['nrms']['auc']) if n else '--'} | "
                 f"{f4(j['results']['rerank']['auc'])} |")
    o += ["", "**Axis 2 — the feature change**, measured on *both* architectures so",
          "the improvement is not a property of one of them:", "",
          "| | architecture | Δ AUC (paired, 95% CI) | Δ nDCG@10 |", "|---|---|---|---|"]
    for d in DS:
        n, b = nrms.get(d), abl.get(d)
        if n and n.get("paired_improvement"):
            p = n["paired_improvement"]
            o.append(f"| {L[d]} | NRMS + freshness | {ci(p.get('auc'))} | {ci(p.get('ndcg@10'))} |")
        if b:
            k = "+ rolling (the improvement)"
            p = b["paired_vs_baseline"].get(k, {})
            o.append(f"| {L[d]} | GBDT + rolling | {ci(p.get('auc'))} | {ci(p.get('ndcg@10'))} |")
    o += ["", "**Leave-one-family-out** — what each kind of signal is worth. Each",
          "variant is retrained, not zeroed at inference: a GBDT picks its splits",
          "with the feature present, so zeroing it later measures a crippled model",
          "rather than one that never had it.", "",
          "| | dropped | AUC | Δ AUC (paired, 95% CI) |", "|---|---|---|---|"]
    for d in DS:
        b = abl.get(d)
        if not b: continue
        for k, r in b["results"].items():
            if not k.startswith("- "): continue
            p = b["paired_vs_baseline"].get(k, {})
            o.append(f"| {L[d]} | `{k[2:]}` | {f4(r['auc'])} | {ci(p.get('auc'))} |")
    o += ["", "## Q3.4 — Statistical significance", "",
          "Every claim above ships a **paired** bootstrap 95% CI on the",
          "per-impression delta. Paired is not a detail: two independent CIs over",
          "the same impressions overstate the uncertainty of their difference,",
          "because the impression-to-impression variance is common to both systems",
          "and cancels only when the resample is shared (`evaluate.paired_bootstrap`).",
          "",
          "Effect sizes are reported next to the intervals. With 244,647 and 73,152",
          "test impressions, thousandths of a point clear significance — that is a",
          "statement about sample size, not about what a user would notice.", ""]
    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text("\n".join(o))
    print(f"wrote {a.out} ({len(o)} lines)")


if __name__ == "__main__":
    main()
