"""Q4: serving and scale. Generated from reports/q4/serving_*.json."""
from __future__ import annotations
import argparse, json
from pathlib import Path

DS = ("ebnerd", "mind")
L = {"ebnerd": "EB-NeRD", "mind": "MIND"}


def load(p): return json.loads(p.read_text()) if p.exists() else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", default="small")
    ap.add_argument("--out", type=Path, default=Path("reports/q4/q4_serving.md"))
    a = ap.parse_args()
    j = {d: load(Path("reports/q4") / f"serving_{d}_{a.variant}.json") for d in DS}

    o = ["# Q4 — Serving and scale", "",
         "Generated by `scripts/q4_report.py`. Timings are from a run with nothing",
         "else scheduled on the box: a latency measured under contention measures",
         "the contention.", "",
         "A1 measured the retrieval service alone — `D_total` 9.19 ms with",
         "`ann_search` the bottleneck at 8.96 ms, service CV 0.01 (so M/D/1, not",
         "M/M/1, which over-predicts wait by 1.9x), and 110 → 467 q/s going from 1",
         "to 48 leaf threads. A2 adds the second stage, so the question is what",
         "re-ranking costs on top and where the budget actually goes.", "",
         "## Q4.1 — Index and feature-store memory", "",
         "| | ANN index | BM25 index | article vectors | feature store (disk) | total resident |",
         "|---|---|---|---|---|---|"]
    for d in DS:
        x = j.get(d)
        if not x: continue
        m = x["memory"]
        o.append(f"| {L[d]} | {m['ann_index']['serialized_mb']} MB "
                 f"({m['ann_index']['n_vectors']:,} vecs) | "
                 f"{m['bm25_index']['csr_mb']} MB ({m['bm25_index']['postings']:,} postings) | "
                 f"{m['article_vectors']['mb']} MB | "
                 f"{m['feature_store']['parquet_on_disk_mb']} MB | "
                 f"{m['total_resident_mb']} MB |")
    o += ["", "## Q4.2 — p99 latency for a single user request", "",
          "Candidate generation **and** re-ranking, per stage and end to end, with",
          "the first requests discarded so BLAS threadpools and the page cache are",
          "warm. Reported as a distribution: the SLA is a p99 and a mean hides",
          "exactly the tail it is about.", "",
          "| | stage | p50 | p95 | **p99** | mean |", "|---|---|---|---|---|---|"]
    for d in DS:
        x = j.get(d)
        if not x: continue
        for s, v in x["latency"].items():
            bold = "**" if s == "end_to_end" else ""
            o.append(f"| {L[d]} | {bold}{s}{bold} | {v['p50_ms']:.3f} | {v['p95_ms']:.3f} | "
                     f"**{v['p99_ms']:.3f}** | {v['mean_ms']:.3f} |")
    o += ["", "The cascade's own argument (L6 s.21) is that the funnel exists because",
          "*feature* cost, not model cost, forbids running the heavy ranker on",
          "everything. That is testable here:", "",
          "| | candidate generation | re-ranking | feature fetch as share of re-ranking |",
          "|---|---|---|---|"]
    for d in DS:
        x = j.get(d)
        if not x: continue
        s = x["stage_split"]
        o.append(f"| {L[d]} | {s['candidate_generation_ms']} ms | {s['reranking_ms']} ms | "
                 f"{s['feature_fetch_share_of_rerank']:.1%} |")
    o += ["", "## Q4.3 — Cost per 1000 queries at the SLA", "",
          "| | p99 | SLA met | q/s single-threaded | cores | q/s per box (ideal) | $ / 1000 queries |",
          "|---|---|---|---|---|---|---|"]
    for d in DS:
        x = j.get(d)
        if not x: continue
        c = x["cost"]
        o.append(f"| {L[d]} | {c['p99_ms']:.2f} ms | {'yes' if c['meets_sla'] else 'NO'} | "
                 f"{c['qps_single_threaded']} | {c['cores']} | {c['qps_per_box_ideal']} | "
                 f"${c['usd_per_1000_queries']:.6f} |")
    o += ["",
          "The per-box figure assumes linear scaling across cores, which is an",
          "upper bound and is stated as one: A1 measured 110 → 467 q/s going from",
          "1 to 48 leaves — 4.23x for 48x the threads. The realistic cost is",
          "several times the number above. The instance price is an assumption and",
          "the answer is linear in it.", "",
          "## Q4.4 — 10x, and what breaks first", "",
          "| what breaks | why | the fix |", "|---|---|---|",
          "| the frozen feature store | popularity is fixed at the split boundary; 84.2% of EB-NeRD candidate slots already score a prior click count of zero, and that fraction grows with catalogue churn | the rolling counters this assignment adds — measured at +0.0509 AUC — but they need a streaming aggregate, not a batch job |",
          "| exact ANN search | A1 measured the flat-vs-HNSW crossover at N≈8,000 and the live universe is already past it at 10x the window | HNSW; A1 measured 9.4x throughput at 125K articles for 96.5% fidelity, and its 42 s single-threaded build becomes the new bottleneck |",
          "| the BM25 matmul | `H·TF` stops fitting at 10x users x 10x vocabulary | blocked product, or WAND once the *universe* grows ~5x — A1 measured that the query path breaks at 10x the universe, not 10x the users |",
          "| the re-rank feature join | the two-stage build OOMed at K=200 over 200k impressions; peak RSS is linear in rows | chunked writes, or the 125 GB box; the in-impression path is far cheaper and is what the leaderboard needs |",
          "| single node | one box, no replication | the one item a single machine cannot measure, stated as a gap rather than estimated |",
          "", "## Q4.5 — Measured benchmark plus argument", "",
          "Both: the tables above are measured on this hardware; the 10x column is",
          "an argument anchored to A1's measured crossovers rather than a guess.", ""]
    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text("\n".join(o))
    print(f"wrote {a.out} ({len(o)} lines)")


if __name__ == "__main__":
    main()
