"""Q5: extended evaluation. Generated from reports/q5/eval_*.json."""
from __future__ import annotations
import argparse, json
from pathlib import Path

DS = ("ebnerd", "mind")
L = {"ebnerd": "EB-NeRD", "mind": "MIND"}
ACC = ("auc", "mrr", "ndcg@5", "ndcg@10")


def load(p): return json.loads(p.read_text()) if p.exists() else None


def cell(r, m):
    v = r.get(m)
    if v is None: return "--"
    c = r.get(f"{m}_ci95")
    return f"{v:.4f} <sub>[{c[0]:.4f}, {c[1]:.4f}]</sub>" if c else f"{v:.4f}"


def beyond(r: dict, m: str, dp: int) -> str:
    """Point estimate plus its 95% interval, for the non-accuracy metrics."""
    v = r.get(m, float("nan"))
    ci = r.get(f"{m}_ci95")
    if not ci:
        return f"{v:.{dp}f}"
    return f"{v:.{dp}f} <sub>[{ci[0]:.{dp}f}, {ci[1]:.{dp}f}]</sub>"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", default="small")
    ap.add_argument("--out", type=Path, default=Path("reports/q5/q5_evaluation.md"))
    a = ap.parse_args()
    j = {d: load(Path("reports/q5") / f"eval_{d}_{a.variant}.json") for d in DS}
    ts = {d: load(Path("reports/q5") / f"eval_{d}_{a.variant}_twostage.json") for d in DS}

    o = ["# Q5 — Extended evaluation", "",
         "Generated by `scripts/q5_report.py`. 95% bootstrap CIs in brackets on",
         "every reported metric, as Q5 requires -- diversity and novelty are",
         "bootstrapped over impressions like the accuracy metrics; coverage is a",
         "union rather than a mean, so its interval comes from resampling",
         "impressions and recomputing the union, which sits below the point",
         "estimate by construction.", "",
         "## All metrics, **full two-stage pipeline**", "",
         "Stage one's real top-K with nothing injected, and every impression kept —",
         "including the ~79% (EB-NeRD) and ~90% (MIND) where retrieval returned no",
         "clicked article at all, which score zero. These numbers are bounded by",
         "recall@K and are **not** comparable to the in-impression table below.",
         "",
         "The arms are trained on the cascade's own candidate distribution. Scoring a",
         "shown-trained model here measures the train/serve mismatch rather than the",
         "pipeline — it put the shipped arm at 0.3981 AUC, below random.",
         "",
         "| | model | AUC | MRR | nDCG@5 | nDCG@10 | ILD@10 | novelty@10 | coverage@10 |",
         "|---|---|---|---|---|---|---|---|---|"]
    for d in DS:
        x = ts.get(d)
        if not x:
            continue
        for n, r in x["overall"].items():
            o.append(f"| {L[d]} | {n} | " + " | ".join(cell(r, m) for m in ACC) +
                     f" | {beyond(r, 'ild@10', 3)}"
                     f" | {beyond(r, 'novelty@10', 2)}"
                     f" | {beyond(r, 'coverage@10', 3)} |")
    o += ["",
          "The AUCs here are structurally inflated and should not be read as quality:",
          "a retrieved negative was never shown to anyone, so any exposure-derived",
          "feature separates it from a clicked positive almost perfectly. nDCG@10 is",
          "the meaningful end-to-end figure, and it is capped by stage-1 recall",
          "(0.2074 / 0.0676).",
          "",
          "## All metrics, in-impression — what the leaderboards score", "",
         "| | model | AUC | MRR | nDCG@5 | nDCG@10 | ILD@10 | novelty@10 | coverage@10 |",
         "|---|---|---|---|---|---|---|---|---|"]
    for d in DS:
        x = j.get(d)
        if not x: continue
        for n, r in x["overall"].items():
            o.append(f"| {L[d]} | {n} | " + " | ".join(cell(r, m) for m in ACC) +
                     f" | {beyond(r, 'ild@10', 3)}"
                     f" | {beyond(r, 'novelty@10', 2)}"
                     f" | {beyond(r, 'coverage@10', 3)} |")
    o += ["",
          "Diversity is the mean over impressions of each list's own intra-list",
          "distance. An earlier pooled estimator stacked the lists into one",
          "matrix, which truncates every list to the shortest in the dataset --",
          "MIND's shortest in-impression list has 2 candidates, so it was",
          "reporting ILD@2 under the name ILD@10. The two agree exactly on the",
          "two-stage sets, where every retrieved list has at least k items.", "",
          "Diversity is intra-list distance in the embedding space rather than over",
          "the category taxonomy: MIND's taxonomy is 18 labels wide and EB-NeRD's is",
          "a different taxonomy, so a category index is not comparable across the",
          "two. Novelty is scored against the click distribution of the window",
          "*before* the split — using in-window popularity would make a system look",
          "novel for surfacing what later turned out to be a hit.", "",
          "## Slices", ""]
    o += ["Both required slices, reported for **both framings**: the two-stage",
          "pipeline (what Q5 asks for) and in-impression (what the leaderboards",
          "score). The slice definitions are identical; only the candidate set",
          "differs, and the two-stage slices are far smaller because an",
          "impression enters only when stage one retrieved something for it.", ""]
    for d in DS:
        for src, lbl in ((ts.get(d), "two-stage"), (j.get(d), "in-impression")):
            if not src: continue
            cd = src.get("cold_definition", {})
            o += [f"**{L[d]} — {lbl}** — cold: `n_hist <= {cd.get('threshold_used')}` "
                  f"({cd.get('impressions_under_fixed_threshold')} impressions fall under the "
                  f"fixed threshold of {cd.get('fixed_threshold')}); "
                  f"head: exposure-at-request >= {src.get('head_exposure_threshold', 0):.0f}", "",
                  "| slice | impressions | model | AUC | nDCG@10 |", "|---|---|---|---|---|"]
            for sl, v in src["slices"].items():
                for n, r in v.items():
                    if n == "n_impressions": continue
                    o.append(f"| {sl} | {v['n_impressions']:,} | {n} | "
                             f"{cell(r, 'auc')} | {cell(r, 'ndcg@10')} |")
            o.append("")
    o += ["## Calibration — what a ranking metric cannot see", "",
          "L7 s.38: a model can order perfectly while every probability it emits is",
          "far from the truth. LambdaRank scores are unbounded reals, not",
          "probabilities; they are squashed logistically purely so the question can",
          "be asked, and a ranking objective is *expected* to fail it. Measured",
          "rather than assumed:", "",
          "| | model | ECE | Brier | mean predicted | base rate |",
          "|---|---|---|---|---|---|"]
    for d in DS:
        for src, lbl in ((ts.get(d), "two-stage"), (j.get(d), "in-impression")):
            if not src:
                continue
            for n, r in src["overall"].items():
                c = r.get("calibration")
                if c:
                    o.append(f"| {L[d]} ({lbl}) | {n} | {c['ece']:.4f} | {c['brier']:.4f} "
                             f"| {c['mean_predicted']:.4f} | {c['base_rate']:.4f} |")
    o += ["",
          "Every arm predicts a click probability two to three orders of magnitude",
          "above the base rate. That is the expected answer for a ranking loss and",
          "the reason nothing here should feed a bid, a blend or a threshold without",
          "Platt or isotonic rescaling on held-out recent data.",
          "",
          "## The head/tail prediction, tested", "",
          "L7 s.40 claims memorised behavioural statistics are unbeatable on the",
          "head and empty on the tail, where only content survives. The two arms",
          "are defined at column level, not by family: the `article` family holds",
          "`age_hours`, which a brand-new article has, and the `match` family holds",
          "`cat_*`, which comes from the user's log.", "",
          "| dataset (framing) | slice | content AUC | article-log AUC | winner |",
          "|---|---|---|---|---|"]
    for d in DS:
        for src, lbl in ((ts.get(d), "two-stage"), (j.get(d), "in-impression")):
            if not src: continue
            for sl, v in src.get("head_tail_verdict", {}).items():
                w = "article-log" if v.get("article_log_wins") else "**content**"
                o.append(f"| {L[d]} ({lbl}) | {sl} | {v['content_auc']:.4f} | "
                         f"{v['article_log_auc']:.4f} | {w} |")
    o += ["",
          "**The verdict depends on the framing, and that is the finding.**",
          "In-impression, content wins all four slices and the lecture's claim is",
          "falsified. Through the cascade, MIND inverts -- article-log wins both",
          "its slices -- because stage one has already removed the articles a",
          "popularity prior would have got wrong, leaving a candidate set on which",
          "memorised exposure separates almost perfectly. EB-NeRD does not invert.",
          "A claim about head and tail is therefore not a property of the data",
          "alone; it is a property of the candidate set the question is asked on.",
          "The two-stage head slice is 837 (EB-NeRD) and 420 (MIND) impressions,",
          "so the inverted cell is the thinnest evidence in this report.", "",
          "**A confound this test cannot escape.** The slice is defined by an",
          "article's exposure count and the article-log arm is built from exposure",
          "counts, so conditioning on the variable removes its variance inside the",
          "slice. Comparing the two arms *within* a slice is meaningful; comparing",
          "one arm *across* slices is not, which is why article-log scoring lower",
          "on the head than the tail is a property of the slicing rather than a",
          "causal statement.", ""]
    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text("\n".join(o))
    print(f"wrote {a.out} ({len(o)} lines)")


if __name__ == "__main__":
    main()
