"""Q5: extended evaluation. Generated from reports/q5/eval_*.json."""
from __future__ import annotations
import argparse, json
from pathlib import Path

DS = ("ebnerd", "mind")
L = {"ebnerd": "EB-NeRD", "mind": "MIND"}
ACC = ("auc", "mrr", "ndcg@5", "ndcg@10")


def load(p): return json.loads(p.read_text()) if p.exists() else None


def cell(r, m):
    v = r.get(m)
    if v is None: return "--"
    c = r.get(f"{m}_ci95")
    return f"{v:.4f} <sub>[{c[0]:.4f}, {c[1]:.4f}]</sub>" if c else f"{v:.4f}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", default="small")
    ap.add_argument("--out", type=Path, default=Path("reports/q5/q5_evaluation.md"))
    a = ap.parse_args()
    j = {d: load(Path("reports/q5") / f"eval_{d}_{a.variant}.json") for d in DS}

    o = ["# Q5 — Extended evaluation", "",
         "Generated by `scripts/q5_report.py`. 95% bootstrap CIs in brackets on",
         "every accuracy metric, as Q5 requires.", "",
         "## All metrics, full two-stage pipeline", "",
         "| | model | AUC | MRR | nDCG@5 | nDCG@10 | ILD@10 | novelty@10 | coverage@10 |",
         "|---|---|---|---|---|---|---|---|---|"]
    for d in DS:
        x = j.get(d)
        if not x: continue
        for n, r in x["overall"].items():
            o.append(f"| {L[d]} | {n} | " + " | ".join(cell(r, m) for m in ACC) +
                     f" | {r.get('ild@10', float('nan')):.3f}"
                     f" | {r.get('novelty@10', float('nan')):.2f}"
                     f" | {r.get('coverage@10', float('nan')):.3f} |")
    o += ["",
          "Diversity is intra-list distance in the embedding space rather than over",
          "the category taxonomy: MIND's taxonomy is 18 labels wide and EB-NeRD's is",
          "a different taxonomy, so a category index is not comparable across the",
          "two. Novelty is scored against the click distribution of the window",
          "*before* the split — using in-window popularity would make a system look",
          "novel for surfacing what later turned out to be a hit.", "",
          "## Slices", ""]
    for d in DS:
        x = j.get(d)
        if not x: continue
        cd = x.get("cold_definition", {})
        o += [f"**{L[d]}** — cold: `n_hist <= {cd.get('threshold_used')}` "
              f"({cd.get('impressions_under_fixed_threshold')} impressions fall under the "
              f"fixed threshold of {cd.get('fixed_threshold')}); "
              f"head: exposure-at-request >= {x.get('head_exposure_threshold', 0):.0f}", "",
              "| slice | impressions | model | AUC | nDCG@10 |", "|---|---|---|---|---|"]
        for s, v in x["slices"].items():
            for n, r in v.items():
                if n == "n_impressions": continue
                o.append(f"| {s} | {v['n_impressions']:,} | {n} | "
                         f"{cell(r, 'auc')} | {cell(r, 'ndcg@10')} |")
        o.append("")
    o += ["## The head/tail prediction, tested", "",
          "L7 s.40 claims memorised behavioural statistics are unbeatable on the",
          "head and empty on the tail, where only content survives. The two arms",
          "are defined at column level, not by family: the `article` family holds",
          "`age_hours`, which a brand-new article has, and the `match` family holds",
          "`cat_*`, which comes from the user's log.", "",
          "| | slice | content AUC | article-log AUC | winner |", "|---|---|---|---|---|"]
    for d in DS:
        x = j.get(d)
        if not x: continue
        for s, v in x.get("head_tail_verdict", {}).items():
            w = "article-log" if v.get("article_log_wins") else "**content**"
            o.append(f"| {L[d]} | {s} | {v['content_auc']:.4f} | "
                     f"{v['article_log_auc']:.4f} | {w} |")
    o += ["",
          "**A confound this test cannot escape.** The slice is defined by an",
          "article's exposure count and the article-log arm is built from exposure",
          "counts, so conditioning on the variable removes its variance inside the",
          "slice. Comparing the two arms *within* a slice is meaningful; comparing",
          "one arm *across* slices is not, which is why article-log scoring lower",
          "on the head than the tail is a property of the slicing rather than a",
          "causal statement.", ""]
    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text("\n".join(o))
    print(f"wrote {a.out} ({len(o)} lines)")


if __name__ == "__main__":
    main()
